### ISSUE TITLE
Automate qURI field

### ISSUE THREAD

**Issue by crockeea** [bstamour/haskell-nist-beacon#3]
Let me preface this by saying I know absolutely _NOTHING_ about XML. To make `getRecord` parse the input, I had to hard-code `(Just "http://beacon.nist.gov/record/0.1/")` into the the `QName` passed to `findChild` (previously the value was `Nothing`). Is there some way to automatically derive this value from the input?

**Comment by bstamour** [comment]
Hey.

Thanks for checking out my little library! I will merge your changes and toss it up on hackage Thursday, if you can wait that long.

Regards,

Bryan St. Amour

On February 23, 2016 5:18:05 PM EST, crockeea notifications@github.com wrote:

> Let me preface this by saying I know absolutely _NOTHING_ about XML. To
> make `getRecord` parse the input, I had to hard-code `(Just
> "http://beacon.nist.gov/record/0.1/")` into the the `QName` passed to
> `findChild` (previously the value was `Nothing`). Is there some way to
> automatically derive this value from the input?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bstamour/haskell-nist-beacon/issues/3

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by crockeea** [comment]
Not a problem. So glad someone else looked into this!

**Comment by crockeea** [comment]
No idea if it helps for this ticket, but the XML "schema" used by the Beacon is [here](https://beacon.nist.gov/record/0.1/beacon-0.1.0.xsd).
